syncobj_enable=1

# animations
animations=0
layer_animations=0

# cursor
cursor_size=24
cursor_theme=capgruv
drag_tile_to_tile=1

# keyboard
xkb_rules_layout=us,ua

# mouse
mouse_accel_profile=0

# appearance
borderpx=1
bordercolor=0x3C3836FF
dropcolor=0x3C3836FF
focuscolor=0xEBDBB2FF

# layout
# tile,scroller,grid,deck,monocle,center_tile,vertical_tile,vertical_scroller
tagrule=id:1,layout_name:dwindle
tagrule=id:2,layout_name:dwindle
tagrule=id:3,layout_name:dwindle
tagrule=id:4,layout_name:dwindle
tagrule=id:5,layout_name:dwindle
tagrule=id:6,layout_name:dwindle
tagrule=id:7,layout_name:dwindle
tagrule=id:8,layout_name:dwindle
tagrule=id:9,layout_name:dwindle

# bindings
bind=SUPER,r,reload_config

bind=Alt,space,spawn,rofi -show drun -no-show-icons
bind=Alt,v,spawn_shell,cliphist list | rofi -dmenu | cliphist decode | wl-copy
bind=Alt,Return,spawn,kitty
bind=Alt+Ctrl,Return,spawn,/home/miha/zen/zen
bind=Alt,e,spawn,env EDITOR=nvim kitty yazi
bind=NONE,Print,spawn_shell,grim -g "$(slurp)" - | swappy -f -
bind=ALT,SHIFT_L,switch_keyboard_layout
bind=ALT,F5,spawn,obs-cmd recording toggle

bind=SUPER,m,quit
bind=ALT,q,killclient,

bind=ALT,H,focusdir,left
bind=ALT,L,focusdir,right
bind=ALT,K,focusdir,up
bind=ALT,J,focusdir,down

bind=SUPER,K,exchange_client,up
bind=SUPER,J,exchange_client,down
bind=SUPER,H,exchange_client,left
bind=SUPER,L,exchange_client,right

bind=ALT,Tab,toggleoverview,
bind=ALT,backslash,togglefloating,
bind=ALT,f,togglefullscreen,
bind=SUPER,i,minimized,

bind=Ctrl,1,view,1,0
bind=Ctrl,2,view,2,0
bind=Ctrl,3,view,3,0
bind=Ctrl,4,view,4,0
bind=Ctrl,5,view,5,0
bind=Ctrl,6,view,6,0
bind=Ctrl,7,view,7,0
bind=Ctrl,8,view,8,0
bind=Ctrl,9,view,9,0

bind=Alt,1,tag,1,0
bind=Alt,2,tag,2,0
bind=Alt,3,tag,3,0
bind=Alt,4,tag,4,0
bind=Alt,5,tag,5,0
bind=Alt,6,tag,6,0
bind=Alt,7,tag,7,0
bind=Alt,8,tag,8,0
bind=Alt,9,tag,9,0

bind=CTRL+SHIFT,Down,movewin,+0,+50
bind=CTRL+SHIFT,Left,movewin,-50,+0
bind=CTRL+SHIFT,Right,movewin,+50,+0

bind=CTRL+ALT,Up,resizewin,+0,-50
bind=CTRL+ALT,Down,resizewin,+0,+50
bind=CTRL+ALT,Left,resizewin,-50,+0
bind=CTRL+ALT,Right,resizewin,+50,+0

mousebind=ALT,btn_left,moveresize,curmove
mousebind=ALT,btn_right,moveresize,curresize

bind=NONE,XF86AudioRaiseVolume,spawn,wpctl set-volume @DEFAULT_SINK@ 5%+
bind=NONE,XF86AudioLowerVolume,spawn,wpctl set-volume @DEFAULT_SINK@ 5%-
bind=NONE,XF86AudioMute,spawn,wpctl set-mute @DEFAULT_SINK@ toggle
bind=SHIFT,XF86AudioMute,spawn,wpctl set-mute @DEFAULT_SOURCE@ toggle

bind=NONE,XF86AudioNext,spawn,playerctl next
bind=NONE,XF86AudioPrev,spawn,playerctl previous
bind=NONE,XF86AudioPlay,spawn,playerctl play-pause

# winodwrules
windowrule=isfloating:1,appid:qalculate-gtk

# startups
exec-once=pipewire
exec-once=pipewire-pulse
exec-once=wireplumber
exec-once=wlr-randr --output HDMI-A-1 --mode 1920x1080@180.003006 --pos 0,0 --on --output eDP-1 --off
exec-once=waybar
exec-once=wl-paste --watch cliphist store
exec-once=awww-daemon
exec-once=awww img /home/miha/Pictures/wallpapers/skies.png
# exec-once=swaync
