# Change the default Omarchy look'n'feel

# https://wiki.hypr.land/Configuring/Basics/Variables/#general
general {
    # No gaps between windows or borders
    # gaps_in = 0
    # gaps_out = 0
    # border_size = 0

    # Change to niri-like side-scrolling layout
    # layout = scrolling
}

# https://wiki.hypr.land/Configuring/Basics/Variables/#decoration
decoration {
    # Use round window corners
    # rounding = 8

    # Dim unfocused windows (0.0 = no dim, 1.0 = fully dimmed)
    # dim_inactive = true
    # dim_strength = 0.15
}

# https://wiki.hypr.land/Configuring/Basics/Variables/#animations
animations {
    # Disable all animations
    # enabled = no
}

# https://wiki.hypr.land/Configuring/Basics/Variables/#layout
layout {
    # Avoid overly wide single-window layouts on wide screens
    # single_window_aspect_ratio = 1 1
}

# https://wiki.hypr.land/Configuring/Layouts/Scrolling-Layout/
scrolling {
    # See only one column per screen instead of two
    # column_width = 0.97
}

general {
  gaps_in = 5
  gaps_out = 10

  col.active_border = rgb(69557c)
}

decoration {
  rounding = 5
  rounding_power = 5

  shadow {
    enabled = true
    range = 4
    render_power = 3
    color = rgba(1a1a1aee)
  }

  blur {
    enabled = true
    size = 3
    passes = 2
    vibrancy = 0.1696
  }
}

windowrule = match:class ^(qalculate-gtk)$, float 1
windowrule = match:class ^(qalculate-gtk)$, center 1
